version: '3.8'
services:
  db:
    image: postgres:9.3
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432"

  web:
    image: miriamtech/table_locks${BUILD_TAG}
    environment:
      PASSENGER_APP_ENV: development
    depends_on:
      - db
    entrypoint: bin/wrap_dev_container
